#!/usr/bin/env bash
# run on phone with curl -sSL bootstrap.connor.engineer/termux | sh

# ncurses prompt for mirrors to use
# choose Rotate then North America
termux-change-repo

pkg update
yes | pkg upgrade

pkg add -y \
	chezmoi \
	git \
	termux-api \
	ruby \
        nnn \
        aria2 \
        curl \
        fd \
        fzf \
        mosh \
        rsync \
        ripgrep \
        vim \
	zoxide \
	fish \
        lf \
        uv \
        screen \
        neovim

#python -m pip install \
#	ipython

gem install \
	highline

rm /data/data/com.termux/files/usr/etc/motd

termux-setup-storage
ln -s $HOME/storage/dcim/notes $HOME/notes

chezmoi init --apply https://github.com/0xConnorRhodes/termux-dotfiles.git

mkdir $HOME/code
git clone 'https://github.com/0xConnorRhodes/sysops-scripts.git' $HOME/code/scripts
git clone 'https://github.com/0xConnorRhodes/ruby-modules.git' $HOME/code/ruby-modules
git clone 'https://github.com/0xConnorRhodes/food-log.git' $HOME/code/food-log

sed -i 's|url = https://github.com/|url = git@github.com:|g' $HOME/.local/share/chezmoi/.git/config
sed -i 's|url = https://github.com/|url = git@github.com:|g' $HOME/code/scripts/.git/config
sed -i 's|url = https://github.com/|url = git@github.com:|g' $HOME/code/ruby-modules/.git/config
sed -i 's|url = https://github.com/|url = git@github.com:|g' $HOME/code/food-log/.git/config

echo ""
echo 'Restart and run `sage` to set age key'
