#!/usr/bin/env bash
# run on phone with curl -sSL bootstrap.connor.engineer/termux | sh

# ncurses prompt for mirrors to use
# choose Rotate then North America
termux-change-repo

pkg update
yes | pkg upgrade

pkg add -y \
	chezmoi \
	git \
	termux-api \
	ruby \
        nnn \
        aria2 \
        curl \
        fd \
        fzf \
        mosh \
        rsync \
        ripgrep \
        vim \
	zoxide \
	fish

#python -m pip install \
#	ipython

gem install \
	highline

termux-setup-storage
ln -s $HOME/storage/dcim/notes $HOME/notes

printf "chezmoi age key: "
read user_input
mkdir -p "$HOME/.local/.secret"
echo "$user_input" > "$HOME/.local/.secret/age-termux-key.txt"

chezmoi init --apply https://github.com/0xConnorRhodes/termux-dotfiles.git

mkdir $HOME/code
git clone 'https://github.com/0xConnorRhodes/sysops-scripts.git' $HOME/code/scripts
git clone 'https://github.com/0xConnorRhodes/ruby-modules.git' $HOME/code/ruby-modules
git clone 'https://github.com/0xConnorRhodes/food-log.git' $HOME/code/food-log

#echo ""
#echo 'Next, Set Password For SSH with `passwd`'
