#!/usr/bin/env bash
# run on phone with curl -sSL sfs.connorrhodes.com/bootstrap/termux.sh | bash

echo 'first run termux-change-repo (default options are sufficient)'
sleep 5

yes | pkg upgrade

pkg add -y \
	openssh \
	chezmoi \
	termux-api \
	croc \
	python \
	ruby \
        nnn \
	fish \
        aria2 \
        lf \
        neovim \
        bat \
        curl \
        fd \
        fzf \
        inetutils \
        just \
        mosh \
        rsync \
        ripgrep \
        screen \
        tree \
        unzip \
        zoxide

python -m pip install \
	ipython

gem install \
	pry

echo 'for ssh set password with password, then run sshd'
