#!/Users/connor.rhodes/.nix-profile/bin/zsh

# Encoding: utf-8
#
# @raycast.title Audio Dispatch Last Item
# @raycast.author Connor Rhodes
# @raycast.description Audio Dispatch Wrapper
# @raycast.mode silent
#
# @raycast.schemaVersion 1

wezterm cli spawn --new-window --cwd "/Users/connor.rhodes/code/audio-dispatch" -- uv run main.py --last > /dev/null
