#!/Users/connor.rhodes/.nix-profile/bin/zsh

# Encoding: utf-8
#
# @raycast.title Clip Dispatch
# @raycast.author Connor Rhodes
# @raycast.description Clip Dispatch Wrapper
# @raycast.mode silent
#
# @raycast.schemaVersion 1

wezterm cli spawn --new-window --cwd "/Users/connor.rhodes/code/clip-dispatch" -- bash -c 'uv run main.py || { echo "Press Enter to close..."; read; }' > /dev/null
