#!/bin/zsh
# Encoding: utf-8
#
# @raycast.title Connect XM3
# @raycast.author Connor Rhodes
# @raycast.description Connect Bluetooth to Sony XM3
# @raycast.mode silent
#
# @raycast.schemaVersion 1

# get mac address of paired devices with: `blueutil --paired`

device="38-18-4c-4b-eb-64" # sony xm3


# Check if Bluetooth is powered off (0)
if [[ $(blueutil --power) -eq 0 ]]; then
  # Turn Bluetooth on
  blueutil --power 1
fi

blueutil --connect "$device"

if [[ $(blueutil --is-connected "$device") -eq 1 ]]; then
  echo "connected"
else
  blueutil --connect "$device"
fi

if [[ $(blueutil --is-connected "$device") -eq 0 ]]; then
  blueutil --connect "$device"
fi
