#!/bin/bash

# This script brings a specific Visual Studio Code window to the front.
# It uses osascript to run AppleScript commands that interact with the UI.

# The name of the window you want to bring to the front.
# We use 'contains' to match flexibly. For example, a window named
# "notes - my_project" will be matched by "notes".

# Encoding: utf-8
#
# @raycast.title LOF Code Notes
# @raycast.author Connor Rhodes
# @raycast.description launch or focus vscode notes
# @raycast.mode silent
#
# @raycast.schemaVersion 1
WINDOW_NAME="notes"

/usr/bin/osascript -e '
on run argv
    set windowName to item 1 of argv
    try
        tell application "Visual Studio Code"
            activate
        end tell

        tell application "System Events"
            tell application process "Code"
                set frontmost to true
                set targetWindow to (first window whose name contains windowName)
                if exists targetWindow then
                    perform action "AXRaise" of targetWindow
                else
                    error "Window not found."
                end if
            end tell
        end tell
    on error
        do shell script "$HOME/.nix-profile/bin/code $HOME/code/notes"
    end try
end run
' "$WINDOW_NAME" > /dev/null
