#!/Users/connor.rhodes/.nix-profile/bin/zsh

# Encoding: utf-8
#
# @raycast.title Open Note
# @raycast.author Connor Rhodes
# @raycast.description open a note in $EDITOR
# @raycast.mode silent
#
# @raycast.schemaVersion 1

wezterm cli spawn --new-window -- /Users/connor.rhodes/code/scripts/bin/on

