#!/Users/connor.rhodes/.nix-profile/bin/zsh

# Encoding: utf-8
#
# @raycast.title Prompter
# @raycast.author Connor Rhodes
# @raycast.description LLM Prompt Generator
# @raycast.mode silent
#
# @raycast.schemaVersion 1

wezterm cli spawn --new-window --cwd "/Users/connor.rhodes/code/prompter" -- uv run main.py > /dev/null
