#!/Users/connor.rhodes/.nix-profile/bin/zsh

# Encoding: utf-8
#
# @raycast.title S2 Attach
# @raycast.author Connor Rhodes
# @raycast.description S2 Attach Wrapper
# @raycast.mode silent
#
# @raycast.schemaVersion 1

wezterm cli spawn --new-window "/Users/connor.rhodes/code/scripts/bin/s2-attach" > /dev/null
